# Generated by Django 4.2.7 on 2023-11-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_movie_genre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="genre",
            field=models.CharField(
                choices=[
                    ("action", "Action"),
                    ("comedy", "Comedy"),
                    ("drama", "Drama"),
                    ("horror", "Horror"),
                    ("romance", "Romance"),
                    ("science_fiction", "Science Fiction"),
                    ("fantasy", "Fantasy"),
                ],
                max_length=100,
            ),
        ),
    ]
